# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: opengraph 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "opengraph"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michael Bleigh"]
  s.date = "2015-04-24"
  s.description = "A very simple Ruby library for parsing Open Graph prototocol information from websites. See http://opengraphprotocol.org for more information."
  s.email = "michael@intridea.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/opengraph.rb",
    "opengraph.gemspec",
    "spec/examples/partial.html",
    "spec/examples/rottentomatoes.html",
    "spec/opengraph_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/intridea/opengraph"
  s.rubygems_version = "2.4.6"
  s.summary = "A very simple Ruby library for parsing Open Graph prototocol information from websites."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 3.4"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.6.6", "~> 1.6"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.8"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2"])
      s.add_development_dependency(%q<webmock>, ["~> 1.21"])
    else
      s.add_dependency(%q<hashie>, ["~> 3.4"])
      s.add_dependency(%q<nokogiri>, [">= 1.6.6", "~> 1.6"])
      s.add_dependency(%q<rest-client>, ["~> 1.8"])
      s.add_dependency(%q<rspec>, ["~> 3.2"])
      s.add_dependency(%q<webmock>, ["~> 1.21"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 3.4"])
    s.add_dependency(%q<nokogiri>, [">= 1.6.6", "~> 1.6"])
    s.add_dependency(%q<rest-client>, ["~> 1.8"])
    s.add_dependency(%q<rspec>, ["~> 3.2"])
    s.add_dependency(%q<webmock>, ["~> 1.21"])
  end
end

